import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "@/styles/globals.css";
import styles from "@/styles/page.module.css";
import { CounterStoreProvider } from "@/providers/counter-store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <CounterStoreProvider>
          <AppRouterCacheProvider>
            <main className={styles.main}>
              <div className={styles.description}>
                <div>
                  <a
                    href="https://sites.temple.edu/templeformularacing/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <Image
                      src="/cropped-TFR-black-300x139.png"
                      alt="TFR Logo"
                      className={styles.vercelLogo}
                      width={100}
                      height={46}
                      priority
                    />
                  </a>
                </div>
              </div>
              {children}
            </main>

          </AppRouterCacheProvider>
        </CounterStoreProvider>
      </body>
    </html>
  );
}
